# Generated by Django 5.1.3 on 2024-11-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
